### ISSUE TITLE
Fix CI for cg-cert-check

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/cg-cert-check#11]
In order to fix the `cg-cert-check`, we want to be able to authenticate with the bosh to check certs.

## Acceptance Criteria
* [x] Running the cg-cert-check, we want ci to successfully pass the staging tasks

--- 

## Security considerations
none

## Implementation sketch
* [ ]

**Comment by spgreenberg** [comment]
The bosh password in staging is out of sync. The cg-cert-check pipeline should be using credhub rather than S3 for these values.

**Comment by spgreenberg** [comment]
Oh wait, that can't happen... I will update the creds in S3.
